ALTER TYPE "AttendanceType" RENAME VALUE 'CHECK_IN' TO 'MORNING_IN';
ALTER TYPE "AttendanceType" RENAME VALUE 'CHECK_OUT' TO 'EVENING_OUT';
ALTER TYPE "AttendanceType" ADD VALUE 'LUNCH_OUT';
ALTER TYPE "AttendanceType" ADD VALUE 'AFTERNOON_IN';
